services:
  postgres:
    image: postgres:15-alpine
    container_name: patient-postgres-new
    # HOST:CONTAINER - You are using 5433 on your laptop, 5432 inside docker
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: patient_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    networks:
      - patient-network

  # --- NEW: pgAdmin Service ---
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - patient-network
  # ---------------------------

  patient-app:
    build: .
    container_name: patient-app
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      # CRITICAL: Inside the network, use the SERVICE NAME 'postgres' and internal port '5432'
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/patient_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - patient-network

networks:
  patient-network:
    driver: bridge